<?php
declare(strict_types=1);

namespace AdminApi\Controller;

use App\Controller\AppController as BaseController;
use Cake\Controller\Component;

class AppController extends BaseController
{
    public function loadComponent(string $name, array $config = []): Component
    {
        return parent::loadComponent($name, $config); // TODO: Change the autogenerated stub
    }
}
