<?php
declare(strict_types=1);

namespace AdminApi\Controller;

use App\Controller\AppController as BaseController;
use Cake\Controller\Component;

class AppController extends BaseController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Authentication.Authentication');
    }
}
