<?php
declare(strict_types=1);

namespace PartnerApi\Controller;

use Cake\Core\Configure;
use SwaggerBake\Lib\Annotation\SwagOperation;

class SwaggerController extends AppController
{
    /**
     * @var \SwaggerBake\Controller\Component\SwaggerUiComponent
     */
    public $SwaggerUi;

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Configure::load('PartnerApi.swagger_bake', 'default' ,false);
        $this->loadComponent('SwaggerBake.SwaggerUi');
    }

    /**
     * Controller action for displaying built-in Swagger UI
     *
     * @SwagOperation(isVisible=false)
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $config = $this->SwaggerUi->getSwaggerBakeConfiguration();
        $title = $config->getTitleFromYml();
        $url = $config->getWebPath();
        $this->set(compact('title', 'url'));
        $doctype = $this->SwaggerUi->getDocType($this->request);
        $this->viewBuilder()->setLayout($config->getLayout($doctype));

        return $this->render($config->getView($doctype));
    }
}
