<?php

namespace AuthenticationApi\Controller;

use AuthenticationApi\Dto\JwkSetResponse;
use AuthenticationApi\Service\JwkSetService;
use Cake\Event\EventInterface;
use SwaggerBake\Lib\Attribute\OpenApiResponse;

class JwksController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Authentication->allowUnauthenticated(['index']);
    }

    /**
     * Returns a JWK Set.
     *
     * @param JwkSetService $service
     * @return void
     * @throws \Cake\Http\Exception\InternalErrorException
     */
    #[OpenApiResponse(schemaType: 'array', schema: JwkSetResponse::class)]
    public function index(JwkSetService $service)
    {
        $this->set('data', $service->keyset()['keys']);
        $this->viewBuilder()->setOption('serialize', 'data');
    }
}
