<?php

namespace AuthenticationApi\Controller;

use Authentication\Authenticator\UnauthenticatedException;
use Authentication\Controller\Component\AuthenticationComponent;
use AuthenticationApi\Dto\UserLoginRequest;
use AuthenticationApi\Service\UserAuthenticationService;
use Cake\Event\EventInterface;
use SwaggerBake\Lib\Attribute\OpenApiDto;
use SwaggerBake\Lib\Attribute\OpenApiResponse;

/**
 * @property AuthenticationComponent $Authentication
 */
class LoginController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Authentication->allowUnauthenticated(['login']);
    }

    /**
     * User Authentication
     *
     * Identifies a user via login credentials and returns a JWT (JSON Web Token) as text/plain.
     *
     * @return \Cake\Http\Response|null|void
     * @throws \Authentication\Authenticator\UnauthenticatedException
     */
    #[OpenApiDto(class: UserLoginRequest::class)]
    #[OpenApiResponse(mimeTypes: ['text/plain'])]
    public function login(UserAuthenticationService $service)
    {
        try {
            return $this->response->withStringBody($service->auth($this));
        } catch (UnauthenticatedException $e) {
            return $this->response->withStringBody($e->getMessage())->withStatus(401);
        }
    }
}
