<?php
declare(strict_types=1);

namespace AuthenticationApi\Controller;

use AdminApi\Controller\AppController;
use Cake\Core\Configure;
use SwaggerBake\Controller\Component\SwaggerUiComponent;
use SwaggerBake\Lib\Attribute\OpenApiOperation;

/**
 * @property SwaggerUiComponent $SwaggerUi
 */
class SwaggerController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Configure::load('AuthenticationApi.swagger_bake', 'default' ,false);
        $this->loadComponent('SwaggerBake.SwaggerUi');
        $this->Authentication->allowUnauthenticated(['index']);
    }

    /**
     * Controller action for displaying built-in Swagger UI
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    #[OpenApiOperation(isVisible: false)]
    public function index()
    {
        $config = $this->SwaggerUi->getSwaggerBakeConfiguration();
        $title = $config->getTitleFromYml();
        $url = $config->getWebPath();
        $this->set(compact('title', 'url'));
        $doctype = $this->SwaggerUi->getDocType($this->request);
        $this->viewBuilder()->setLayout($config->getLayout($doctype));

        if ($doctype === 'swagger') {
            return $this->render('Swagger/index');
        }

        return $this->render($config->getView($doctype));
    }
}
