<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Actors seed.
 */
class ActorsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'first_name' => 'PENELOPE',
                'last_name' => 'GUINESS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '2',
                'first_name' => 'NICK',
                'last_name' => 'WAHLBERG',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '3',
                'first_name' => 'ED',
                'last_name' => 'CHASE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '4',
                'first_name' => 'JENNIFER',
                'last_name' => 'DAVIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '5',
                'first_name' => 'JOHNNY',
                'last_name' => 'LOLLOBRIGIDA',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '6',
                'first_name' => 'BETTE',
                'last_name' => 'NICHOLSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '7',
                'first_name' => 'GRACE',
                'last_name' => 'MOSTEL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '8',
                'first_name' => 'MATTHEW',
                'last_name' => 'JOHANSSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '9',
                'first_name' => 'JOE',
                'last_name' => 'SWANK',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '10',
                'first_name' => 'CHRISTIAN',
                'last_name' => 'GABLE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '11',
                'first_name' => 'ZERO',
                'last_name' => 'CAGE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '12',
                'first_name' => 'KARL',
                'last_name' => 'BERRY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '13',
                'first_name' => 'UMA',
                'last_name' => 'WOOD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '14',
                'first_name' => 'VIVIEN',
                'last_name' => 'BERGEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '15',
                'first_name' => 'CUBA',
                'last_name' => 'OLIVIER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '16',
                'first_name' => 'FRED',
                'last_name' => 'COSTNER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '17',
                'first_name' => 'HELEN',
                'last_name' => 'VOIGHT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '18',
                'first_name' => 'DAN',
                'last_name' => 'TORN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '19',
                'first_name' => 'BOB',
                'last_name' => 'FAWCETT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '20',
                'first_name' => 'LUCILLE',
                'last_name' => 'TRACY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '21',
                'first_name' => 'KIRSTEN',
                'last_name' => 'PALTROW',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '22',
                'first_name' => 'ELVIS',
                'last_name' => 'MARX',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '23',
                'first_name' => 'SANDRA',
                'last_name' => 'KILMER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '24',
                'first_name' => 'CAMERON',
                'last_name' => 'STREEP',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '25',
                'first_name' => 'KEVIN',
                'last_name' => 'BLOOM',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '26',
                'first_name' => 'RIP',
                'last_name' => 'CRAWFORD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '27',
                'first_name' => 'JULIA',
                'last_name' => 'MCQUEEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '28',
                'first_name' => 'WOODY',
                'last_name' => 'HOFFMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '29',
                'first_name' => 'ALEC',
                'last_name' => 'WAYNE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '30',
                'first_name' => 'SANDRA',
                'last_name' => 'PECK',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '31',
                'first_name' => 'SISSY',
                'last_name' => 'SOBIESKI',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '32',
                'first_name' => 'TIM',
                'last_name' => 'HACKMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '33',
                'first_name' => 'MILLA',
                'last_name' => 'PECK',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '34',
                'first_name' => 'AUDREY',
                'last_name' => 'OLIVIER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '35',
                'first_name' => 'JUDY',
                'last_name' => 'DEAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '36',
                'first_name' => 'BURT',
                'last_name' => 'DUKAKIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '37',
                'first_name' => 'VAL',
                'last_name' => 'BOLGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '38',
                'first_name' => 'TOM',
                'last_name' => 'MCKELLEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '39',
                'first_name' => 'GOLDIE',
                'last_name' => 'BRODY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '40',
                'first_name' => 'JOHNNY',
                'last_name' => 'CAGE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '41',
                'first_name' => 'JODIE',
                'last_name' => 'DEGENERES',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '42',
                'first_name' => 'TOM',
                'last_name' => 'MIRANDA',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '43',
                'first_name' => 'KIRK',
                'last_name' => 'JOVOVICH',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '44',
                'first_name' => 'NICK',
                'last_name' => 'STALLONE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '45',
                'first_name' => 'REESE',
                'last_name' => 'KILMER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '46',
                'first_name' => 'PARKER',
                'last_name' => 'GOLDBERG',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '47',
                'first_name' => 'JULIA',
                'last_name' => 'BARRYMORE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '48',
                'first_name' => 'FRANCES',
                'last_name' => 'DAY-LEWIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '49',
                'first_name' => 'ANNE',
                'last_name' => 'CRONYN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '50',
                'first_name' => 'NATALIE',
                'last_name' => 'HOPKINS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '51',
                'first_name' => 'GARY',
                'last_name' => 'PHOENIX',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '52',
                'first_name' => 'CARMEN',
                'last_name' => 'HUNT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '53',
                'first_name' => 'MENA',
                'last_name' => 'TEMPLE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '54',
                'first_name' => 'PENELOPE',
                'last_name' => 'PINKETT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '55',
                'first_name' => 'FAY',
                'last_name' => 'KILMER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '56',
                'first_name' => 'DAN',
                'last_name' => 'HARRIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '57',
                'first_name' => 'JUDE',
                'last_name' => 'CRUISE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '58',
                'first_name' => 'CHRISTIAN',
                'last_name' => 'AKROYD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '59',
                'first_name' => 'DUSTIN',
                'last_name' => 'TAUTOU',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '60',
                'first_name' => 'HENRY',
                'last_name' => 'BERRY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '61',
                'first_name' => 'CHRISTIAN',
                'last_name' => 'NEESON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '62',
                'first_name' => 'JAYNE',
                'last_name' => 'NEESON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '63',
                'first_name' => 'CAMERON',
                'last_name' => 'WRAY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '64',
                'first_name' => 'RAY',
                'last_name' => 'JOHANSSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '65',
                'first_name' => 'ANGELA',
                'last_name' => 'HUDSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '66',
                'first_name' => 'MARY',
                'last_name' => 'TANDY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '67',
                'first_name' => 'JESSICA',
                'last_name' => 'BAILEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '68',
                'first_name' => 'RIP',
                'last_name' => 'WINSLET',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '69',
                'first_name' => 'KENNETH',
                'last_name' => 'PALTROW',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '70',
                'first_name' => 'MICHELLE',
                'last_name' => 'MCCONAUGHEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '71',
                'first_name' => 'ADAM',
                'last_name' => 'GRANT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '72',
                'first_name' => 'SEAN',
                'last_name' => 'WILLIAMS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '73',
                'first_name' => 'GARY',
                'last_name' => 'PENN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '74',
                'first_name' => 'MILLA',
                'last_name' => 'KEITEL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '75',
                'first_name' => 'BURT',
                'last_name' => 'POSEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '76',
                'first_name' => 'ANGELINA',
                'last_name' => 'ASTAIRE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '77',
                'first_name' => 'CARY',
                'last_name' => 'MCCONAUGHEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '78',
                'first_name' => 'GROUCHO',
                'last_name' => 'SINATRA',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '79',
                'first_name' => 'MAE',
                'last_name' => 'HOFFMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '80',
                'first_name' => 'RALPH',
                'last_name' => 'CRUZ',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '81',
                'first_name' => 'SCARLETT',
                'last_name' => 'DAMON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '82',
                'first_name' => 'WOODY',
                'last_name' => 'JOLIE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '83',
                'first_name' => 'BEN',
                'last_name' => 'WILLIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '84',
                'first_name' => 'JAMES',
                'last_name' => 'PITT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '85',
                'first_name' => 'MINNIE',
                'last_name' => 'ZELLWEGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '86',
                'first_name' => 'GREG',
                'last_name' => 'CHAPLIN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '87',
                'first_name' => 'SPENCER',
                'last_name' => 'PECK',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '88',
                'first_name' => 'KENNETH',
                'last_name' => 'PESCI',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '89',
                'first_name' => 'CHARLIZE',
                'last_name' => 'DENCH',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '90',
                'first_name' => 'SEAN',
                'last_name' => 'GUINESS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '91',
                'first_name' => 'CHRISTOPHER',
                'last_name' => 'BERRY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '92',
                'first_name' => 'KIRSTEN',
                'last_name' => 'AKROYD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '93',
                'first_name' => 'ELLEN',
                'last_name' => 'PRESLEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '94',
                'first_name' => 'KENNETH',
                'last_name' => 'TORN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '95',
                'first_name' => 'DARYL',
                'last_name' => 'WAHLBERG',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '96',
                'first_name' => 'GENE',
                'last_name' => 'WILLIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '97',
                'first_name' => 'MEG',
                'last_name' => 'HAWKE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '98',
                'first_name' => 'CHRIS',
                'last_name' => 'BRIDGES',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '99',
                'first_name' => 'JIM',
                'last_name' => 'MOSTEL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '100',
                'first_name' => 'SPENCER',
                'last_name' => 'DEPP',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '101',
                'first_name' => 'SUSAN',
                'last_name' => 'DAVIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '102',
                'first_name' => 'WALTER',
                'last_name' => 'TORN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '103',
                'first_name' => 'MATTHEW',
                'last_name' => 'LEIGH',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '104',
                'first_name' => 'PENELOPE',
                'last_name' => 'CRONYN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '105',
                'first_name' => 'SIDNEY',
                'last_name' => 'CROWE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '106',
                'first_name' => 'GROUCHO',
                'last_name' => 'DUNST',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '107',
                'first_name' => 'GINA',
                'last_name' => 'DEGENERES',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '108',
                'first_name' => 'WARREN',
                'last_name' => 'NOLTE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '109',
                'first_name' => 'SYLVESTER',
                'last_name' => 'DERN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '110',
                'first_name' => 'SUSAN',
                'last_name' => 'DAVIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '111',
                'first_name' => 'CAMERON',
                'last_name' => 'ZELLWEGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '112',
                'first_name' => 'RUSSELL',
                'last_name' => 'BACALL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '113',
                'first_name' => 'MORGAN',
                'last_name' => 'HOPKINS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '114',
                'first_name' => 'MORGAN',
                'last_name' => 'MCDORMAND',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '115',
                'first_name' => 'HARRISON',
                'last_name' => 'BALE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '116',
                'first_name' => 'DAN',
                'last_name' => 'STREEP',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '117',
                'first_name' => 'RENEE',
                'last_name' => 'TRACY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '118',
                'first_name' => 'CUBA',
                'last_name' => 'ALLEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '119',
                'first_name' => 'WARREN',
                'last_name' => 'JACKMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '120',
                'first_name' => 'PENELOPE',
                'last_name' => 'MONROE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '121',
                'first_name' => 'LIZA',
                'last_name' => 'BERGMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '122',
                'first_name' => 'SALMA',
                'last_name' => 'NOLTE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '123',
                'first_name' => 'JULIANNE',
                'last_name' => 'DENCH',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '124',
                'first_name' => 'SCARLETT',
                'last_name' => 'BENING',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '125',
                'first_name' => 'ALBERT',
                'last_name' => 'NOLTE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '126',
                'first_name' => 'FRANCES',
                'last_name' => 'TOMEI',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '127',
                'first_name' => 'KEVIN',
                'last_name' => 'GARLAND',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '128',
                'first_name' => 'CATE',
                'last_name' => 'MCQUEEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '129',
                'first_name' => 'DARYL',
                'last_name' => 'CRAWFORD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '130',
                'first_name' => 'GRETA',
                'last_name' => 'KEITEL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '131',
                'first_name' => 'JANE',
                'last_name' => 'JACKMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '132',
                'first_name' => 'ADAM',
                'last_name' => 'HOPPER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '133',
                'first_name' => 'RICHARD',
                'last_name' => 'PENN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '134',
                'first_name' => 'GENE',
                'last_name' => 'HOPKINS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '135',
                'first_name' => 'RITA',
                'last_name' => 'REYNOLDS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '136',
                'first_name' => 'ED',
                'last_name' => 'MANSFIELD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '137',
                'first_name' => 'MORGAN',
                'last_name' => 'WILLIAMS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '138',
                'first_name' => 'LUCILLE',
                'last_name' => 'DEE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '139',
                'first_name' => 'EWAN',
                'last_name' => 'GOODING',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '140',
                'first_name' => 'WHOOPI',
                'last_name' => 'HURT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '141',
                'first_name' => 'CATE',
                'last_name' => 'HARRIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '142',
                'first_name' => 'JADA',
                'last_name' => 'RYDER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '143',
                'first_name' => 'RIVER',
                'last_name' => 'DEAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '144',
                'first_name' => 'ANGELA',
                'last_name' => 'WITHERSPOON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '145',
                'first_name' => 'KIM',
                'last_name' => 'ALLEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '146',
                'first_name' => 'ALBERT',
                'last_name' => 'JOHANSSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '147',
                'first_name' => 'FAY',
                'last_name' => 'WINSLET',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '148',
                'first_name' => 'EMILY',
                'last_name' => 'DEE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '149',
                'first_name' => 'RUSSELL',
                'last_name' => 'TEMPLE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '150',
                'first_name' => 'JAYNE',
                'last_name' => 'NOLTE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '151',
                'first_name' => 'GEOFFREY',
                'last_name' => 'HESTON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '152',
                'first_name' => 'BEN',
                'last_name' => 'HARRIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '153',
                'first_name' => 'MINNIE',
                'last_name' => 'KILMER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '154',
                'first_name' => 'MERYL',
                'last_name' => 'GIBSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '155',
                'first_name' => 'IAN',
                'last_name' => 'TANDY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '156',
                'first_name' => 'FAY',
                'last_name' => 'WOOD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '157',
                'first_name' => 'GRETA',
                'last_name' => 'MALDEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '158',
                'first_name' => 'VIVIEN',
                'last_name' => 'BASINGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '159',
                'first_name' => 'LAURA',
                'last_name' => 'BRODY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '160',
                'first_name' => 'CHRIS',
                'last_name' => 'DEPP',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '161',
                'first_name' => 'HARVEY',
                'last_name' => 'HOPE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '162',
                'first_name' => 'OPRAH',
                'last_name' => 'KILMER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '163',
                'first_name' => 'CHRISTOPHER',
                'last_name' => 'WEST',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '164',
                'first_name' => 'HUMPHREY',
                'last_name' => 'WILLIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '165',
                'first_name' => 'AL',
                'last_name' => 'GARLAND',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '166',
                'first_name' => 'NICK',
                'last_name' => 'DEGENERES',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '167',
                'first_name' => 'LAURENCE',
                'last_name' => 'BULLOCK',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '168',
                'first_name' => 'WILL',
                'last_name' => 'WILSON',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '169',
                'first_name' => 'KENNETH',
                'last_name' => 'HOFFMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '170',
                'first_name' => 'MENA',
                'last_name' => 'HOPPER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '171',
                'first_name' => 'OLYMPIA',
                'last_name' => 'PFEIFFER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '172',
                'first_name' => 'GROUCHO',
                'last_name' => 'WILLIAMS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '173',
                'first_name' => 'ALAN',
                'last_name' => 'DREYFUSS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '174',
                'first_name' => 'MICHAEL',
                'last_name' => 'BENING',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '175',
                'first_name' => 'WILLIAM',
                'last_name' => 'HACKMAN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '176',
                'first_name' => 'JON',
                'last_name' => 'CHASE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '177',
                'first_name' => 'GENE',
                'last_name' => 'MCKELLEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '178',
                'first_name' => 'LISA',
                'last_name' => 'MONROE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '179',
                'first_name' => 'ED',
                'last_name' => 'GUINESS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '180',
                'first_name' => 'JEFF',
                'last_name' => 'SILVERSTONE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '181',
                'first_name' => 'MATTHEW',
                'last_name' => 'CARREY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '182',
                'first_name' => 'DEBBIE',
                'last_name' => 'AKROYD',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '183',
                'first_name' => 'RUSSELL',
                'last_name' => 'CLOSE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '184',
                'first_name' => 'HUMPHREY',
                'last_name' => 'GARLAND',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '185',
                'first_name' => 'MICHAEL',
                'last_name' => 'BOLGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '186',
                'first_name' => 'JULIA',
                'last_name' => 'ZELLWEGER',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '187',
                'first_name' => 'RENEE',
                'last_name' => 'BALL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '188',
                'first_name' => 'ROCK',
                'last_name' => 'DUKAKIS',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '189',
                'first_name' => 'CUBA',
                'last_name' => 'BIRCH',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '190',
                'first_name' => 'AUDREY',
                'last_name' => 'BAILEY',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '191',
                'first_name' => 'GREGORY',
                'last_name' => 'GOODING',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '192',
                'first_name' => 'JOHN',
                'last_name' => 'SUVARI',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '193',
                'first_name' => 'BURT',
                'last_name' => 'TEMPLE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '194',
                'first_name' => 'MERYL',
                'last_name' => 'ALLEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '195',
                'first_name' => 'JAYNE',
                'last_name' => 'SILVERSTONE',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '196',
                'first_name' => 'BELA',
                'last_name' => 'WALKEN',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '197',
                'first_name' => 'REESE',
                'last_name' => 'WEST',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '198',
                'first_name' => 'MARY',
                'last_name' => 'KEITEL',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '199',
                'first_name' => 'JULIA',
                'last_name' => 'FAWCETT',
                'modified' => '2006-02-15 04:34:33',
            ],
            [
                'id' => '200',
                'first_name' => 'THORA',
                'last_name' => 'TEMPLE',
                'modified' => '2006-02-15 04:34:33',
            ],
        ];

        $table = $this->table('actors');
        $table->insert($data)->save();
    }
}
